import type { components } from './generated/openapi'

export type ApiSchemas = components['schemas']

export type ApiError = ApiSchemas['ApiError']
export type ApiMeta = ApiSchemas['DataProvenance']
export type ApiDataMode = ApiSchemas['DataMode']
export type ApiImpact = ApiSchemas['Impact']
export type ApiReviewStatus = ApiSchemas['ReviewStatus']
export type ApiAnalysisStatus = ApiSchemas['AnalysisStatus']
export type ApiInstrumentType = ApiSchemas['InstrumentType']

export type ApiAgentRun = ApiSchemas['AgentRun']
export type ApiAgentRunStep = ApiSchemas['AgentRunStep']
export type ApiArticle = ApiSchemas['Article']
export type ApiAssetRef = ApiSchemas['AssetRef']
export type ApiAssetRelation = ApiSchemas['AssetRelation']
export type ApiBriefing = ApiSchemas['Briefing']
export type ApiBriefingRequest = ApiSchemas['BriefingRequest']
export type ApiEvent = ApiSchemas['Event']
export type ApiEventView = ApiSchemas['EventView']
export type ApiEvidence = ApiSchemas['Evidence']
export type ApiMarketSnapshot = ApiSchemas['MarketSnapshot']
export type ApiMarketSnapshotListResponse = ApiSchemas['MarketSnapshotListResponse']
export type ApiPrioritizedSignal = ApiSchemas['PrioritizedSignal']
export type ApiReviewRequest = ApiSchemas['ReviewRequest']
export type ApiReviewSummary = ApiSchemas['ReviewSummary']
export type ApiReviewTask = ApiSchemas['ReviewTask']
export type ApiSignal = ApiSchemas['Signal']
export type ApiSignalReview = ApiSchemas['SignalReview']
export type ApiSource = ApiSchemas['Source']
export type ApiSseEvent = ApiSchemas['SseEvent']
export type ApiWatchlist = ApiSchemas['Watchlist']
